# Jekyll configuration
name: Power of DevOps Community
url: https://web.powerofdevops.com
markdown: GFM
timezone: Europe/Berlin
title: null # to remove the header

theme: jekyll-theme-primer # default theme for GitHub Pages
