# Jekyll configuration
name: Power of DevOps Community
title: Power of DevOps Community
url: https://web.powerofdevops.com
markdown: GFM
timezone: Europe/Berlin
lang: de-DE
title: null # to remove the header
description: We are a community of German-speaking Azure DevOps enthusiasts

theme: jekyll-theme-primer # default theme for GitHub Pages
